;!knitout-2
;;Machine: kniterate
;;Carriers: 1 2 3 4 5 6
x-stitch-number 5
x-speed-number 100
x-vis-color #000000 1
x-vis-color #ffffff 2
x-vis-color #00e4ff 3
;background color: 2
in 1
knit + f13 1
knit + b19 1
knit + f25 1
knit + b31 1
knit + f37 1
knit - b37 1
knit - f31 1
knit - b25 1
knit - f19 1
knit - b13 1
knit + f13 1
knit + b19 1
knit + f25 1
knit + b31 1
knit + f37 1
knit - b37 1
knit - f31 1
knit - b25 1
knit - f19 1
knit - b13 1
in 2
knit + f14 2
knit + b20 2
knit + f26 2
knit + b32 2
knit + f38 2
knit - b38 2
knit - f32 2
knit - b26 2
knit - f20 2
knit - b14 2
miss - f13 2
knit + f14 2
knit + b20 2
knit + f26 2
knit + b32 2
knit + f38 2
knit - b38 2
knit - f32 2
knit - b26 2
knit - f20 2
knit - b14 2
miss - f13 2
in 3
knit + f15 3
knit + b21 3
knit + f27 3
knit + b33 3
knit - f33 3
knit - b27 3
knit - f21 3
knit - b15 3
miss - f13 3
knit + f15 3
knit + b21 3
knit + f27 3
knit + b33 3
knit - f33 3
knit - b27 3
knit - f21 3
knit - b15 3
miss - f13 3
knit + f15 3
knit + b21 3
knit + f27 3
knit + b33 3
miss + f38 3
in 4
knit + f16 4
knit + b22 4
knit + f28 4
knit + b34 4
knit - f34 4
knit - b28 4
knit - f22 4
knit - b16 4
miss - f13 4
knit + f16 4
knit + b22 4
knit + f28 4
knit + b34 4
knit - f34 4
knit - b28 4
knit - f22 4
knit - b16 4
miss - f13 4
;kniterate yarns in
x-roller-advance 150
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
knit + f13 1
knit + b14 1
knit + f15 1
knit + b16 1
knit + f17 1
knit + b18 1
knit + f19 1
knit + b20 1
knit + f21 1
knit + b22 1
knit + f23 1
knit + b24 1
knit + f25 1
knit + b26 1
knit + f27 1
knit + b28 1
knit + f29 1
knit + b30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b34 1
knit + f35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit - f38 1
knit - b37 1
knit - f36 1
knit - b35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - b31 1
knit - f30 1
knit - b29 1
knit - f28 1
knit - b27 1
knit - f26 1
knit - b25 1
knit - f24 1
knit - b23 1
knit - f22 1
knit - b21 1
knit - f20 1
knit - b19 1
knit - f18 1
knit - b17 1
knit - f16 1
knit - b15 1
knit - f14 1
knit - b13 1
x-roller-advance 100
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
knit + f13 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + f38 1
knit - b38 1
knit - b37 1
knit - b36 1
knit - b35 1
knit - b34 1
knit - b33 1
knit - b32 1
knit - b31 1
knit - b30 1
knit - b29 1
knit - b28 1
knit - b27 1
knit - b26 1
knit - b25 1
knit - b24 1
knit - b23 1
knit - b22 1
knit - b21 1
knit - b20 1
knit - b19 1
knit - b18 1
knit - b17 1
knit - b16 1
knit - b15 1
knit - b14 1
knit - b13 1
drop b13
drop b14
drop b15
drop b16
drop b17
drop b18
drop b19
drop b20
drop b21
drop b22
drop b23
drop b24
drop b25
drop b26
drop b27
drop b28
drop b29
drop b30
drop b31
drop b32
drop b33
drop b34
drop b35
drop b36
drop b37
drop b38
;draw thread: 4
knit + f13 4
knit + f14 4
knit + f15 4
knit + f16 4
knit + f17 4
knit + f18 4
knit + f19 4
knit + f20 4
knit + f21 4
knit + f22 4
knit + f23 4
knit + f24 4
knit + f25 4
knit + f26 4
knit + f27 4
knit + f28 4
knit + f29 4
knit + f30 4
knit + f31 4
knit + f32 4
knit + f33 4
knit + f34 4
knit + f35 4
knit + f36 4
knit + f37 4
knit + f38 4
rack 0.25
knit + f13 1
knit + b13 1
knit + f14 1
knit + b14 1
knit + f15 1
knit + b15 1
knit + f16 1
knit + b16 1
knit + f17 1
knit + b17 1
knit + f18 1
knit + b18 1
knit + f19 1
knit + b19 1
knit + f20 1
knit + b20 1
knit + f21 1
knit + b21 1
knit + f22 1
knit + b22 1
knit + f23 1
knit + b23 1
knit + f24 1
knit + b24 1
knit + f25 1
knit + b25 1
knit + f26 1
knit + b26 1
knit + f27 1
knit + b27 1
knit + f28 1
knit + b28 1
knit + f29 1
knit + b29 1
knit + f30 1
knit + b30 1
knit + f31 1
knit + b31 1
knit + f32 1
knit + b32 1
knit + f33 1
knit + b33 1
knit + f34 1
knit + b34 1
knit + f35 1
knit + b35 1
knit + f36 1
knit + b36 1
knit + f37 1
knit + b37 1
knit + f38 1
knit + b38 1
rack 0

;pass: 1 
knit - f36 1
knit - f35 1
knit - f34 1
knit - b33 1
knit - b30 1
knit - f28 1
knit - b27 1
knit - b24 1
knit - b21 1
knit - f18 1
knit - f17 1
knit - b15 1
miss - f13 1
miss - f12 1
;pass: 2 
knit + b13 2
knit + f15 2
knit + b16 2
knit + b18 2
knit + b19 2
knit + b22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + b28 2
knit + f30 2
knit + b31 2
knit + f32 2
knit + f33 2
knit + b34 2
knit + b36 2
knit + b37 2
miss + f38 2
;pass: 3 
knit - f38 3
knit - f37 3
knit - b35 3
knit - b32 3
knit - f31 3
knit - f29 3
knit - f27 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - b17 3
knit - f16 3
knit - f14 3
knit - f13 3
miss - f12 3
x-speed-number 100
;inc 1 on left
rack -1
xfer b13 f12
rack 0
x-add-roller-advance -100
miss + f13 3
xfer f13 b13
xfer f12 b12
rack -1
xfer b13 f12
rack 0
x-speed-number 100
;pass: 4 
knit + b12 1
knit + b14 1
knit + b15 1
knit + f18 1
knit + b20 1
knit + f21 1
knit + b24 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + b30 1
knit + b33 1
knit + f34 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + b38 1
miss + f39 1
x-roller-advance 50
;pass: 5 
knit - b37 2
knit - b36 2
knit - b34 2
knit - f33 2
knit - f32 2
knit - b31 2
knit - b28 2
knit - b27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - b21 2
knit - b19 2
knit - b18 2
knit - b16 2
knit - f14 2
miss - b13 2
knit + b13 2
miss - f12 2
miss - f11 2
x-roller-advance 100
x-roller-advance 50
;pass: 6 
knit + f12 3
miss + f13 3
knit - f13 3
knit + b14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f19 3
knit + f20 3
knit + b22 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + f29 3
knit + f30 3
knit + f31 3
knit + b32 3
knit + b35 3
knit + f38 3
miss + f39 3
x-roller-advance 100
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
x-roller-advance 50
;pass: 7 
knit + b39 1
knit - b38 1
knit - b36 1
knit - f33 1
knit - b30 1
knit - b29 1
knit - b27 1
knit - b24 1
knit - b21 1
knit - b20 1
knit - f19 1
knit - f18 1
knit - f17 1
knit - b15 1
knit - f12 1
miss - f11 1
knit + f11 1
x-roller-advance 100
x-roller-advance 100
;pass: 8 
knit + b12 2
knit + f13 2
knit + f14 2
knit + f16 2
knit + b17 2
knit + b18 2
knit + b19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + b33 2
knit + b34 2
knit + f35 2
knit + f37 2
knit + f38 2
miss + f39 2
x-roller-advance 50
x-roller-advance 50
;pass: 9 
knit + f39 3
knit - b38 3
knit - b37 3
knit - f36 3
knit - b35 3
knit - f34 3
knit - b32 3
knit - b31 3
knit - f29 3
knit - b28 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - b22 3
knit - b20 3
knit - b17 3
knit - b16 3
knit - f15 3
knit - b14 3
knit - b13 3
miss - b11 3
knit + b11 3
x-roller-advance 100
x-roller-advance 100
;pass: 10 
knit + b12 1
knit + f14 1
knit + f15 1
knit + b18 1
knit + f21 1
knit + f22 1
knit + b24 1
knit + f26 1
knit + b27 1
knit + b29 1
knit + b30 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b36 1
knit + f39 1
miss + f40 1
;pass: 11 
knit - b39 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - b34 2
knit - b33 2
knit - b31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - b22 2
knit - b21 2
knit - f19 2
knit - f17 2
knit - f16 2
knit - b15 2
knit - b13 2
knit - f12 2
miss - f11 2
miss - f10 2
;pass: 12 
knit + f11 3
knit + f13 3
knit + b14 3
knit + b16 3
knit + b17 3
knit + f18 3
knit + b19 3
knit + f20 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + f27 3
knit + b28 3
knit + b29 3
knit + f31 3
knit + b32 3
knit + b35 3
knit + b37 3
knit + f38 3
miss + f39 3
miss + f40 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
;pass: 13 
knit - f39 1
knit - f38 1
knit - b36 1
knit - f35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - b27 1
knit - b24 1
knit - f23 1
knit - f22 1
knit - f21 1
knit - f20 1
knit - b18 1
knit - f15 1
knit - f14 1
knit - f13 1
knit - b12 1
knit - b11 1
miss - f10 1
x-roller-advance 50
x-roller-advance 50
;pass: 14 
knit - f10 2
knit + f11 2
knit + f12 2
knit + b13 2
knit + b15 2
knit + b16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + b20 2
knit + b21 2
knit + b22 2
knit + b25 2
knit + b28 2
knit + f29 2
knit + f30 2
knit + b31 2
knit + f33 2
knit + b34 2
knit + f36 2
knit + f37 2
knit + b38 2
knit + b39 2
miss + f40 2
knit - f40 2
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
x-roller-advance 50
;pass: 15 
knit + b40 3
knit - b38 3
knit - b37 3
knit - b35 3
knit - b32 3
knit - b29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - b23 3
knit - b20 3
knit - b19 3
knit - b17 3
knit - f16 3
knit - b14 3
knit - b11 3
miss - b10 3
knit + b10 3
x-roller-advance 100
x-roller-advance 100
;pass: 16 
knit + b12 1
knit + f13 1
knit + b15 1
knit + b18 1
knit + f20 1
knit + b21 1
knit + b24 1
knit + b26 1
knit + b27 1
knit + b30 1
knit + f31 1
knit + f33 1
knit + b36 1
knit + f38 1
knit + b39 1
knit + f40 1
miss + f41 1
;pass: 17 
knit - b40 2
knit - f39 2
knit - b37 2
knit - b34 2
knit - b33 2
knit - f32 2
knit - b31 2
knit - f30 2
knit - b28 2
knit - f27 2
knit - b25 2
knit - b22 2
knit - f21 2
knit - b19 2
knit - f18 2
knit - b16 2
knit - f14 2
knit - b13 2
knit - f11 2
knit - b10 2
miss - f9 2
;pass: 18 
knit + f10 3
knit + b11 3
knit + f12 3
knit + b14 3
knit + f15 3
knit + f16 3
knit + f17 3
knit + f19 3
knit + b20 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f28 3
knit + f29 3
knit + b32 3
knit + f34 3
knit + f35 3
knit + f36 3
knit + f37 3
knit + b38 3
miss + f40 3
miss + f41 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
x-roller-advance 50
;pass: 19 
knit + b41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - b36 1
knit - b35 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - b29 1
knit - b27 1
knit - b26 1
knit - b24 1
knit - b23 1
knit - b21 1
knit - b18 1
knit - b17 1
knit - b15 1
knit - f14 1
knit - f13 1
knit - b12 1
miss - b9 1
knit + b9 1
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
;pass: 20 
knit - f9 2
knit + f10 2
knit + f12 2
knit + b13 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + b22 2
knit + f23 2
knit + b25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + b31 2
knit + b33 2
knit + b34 2
knit + f37 2
knit + b39 2
knit + b40 2
miss + f41 2
x-roller-advance 100
x-roller-advance 50
;pass: 21 
knit + f41 3
knit - b38 3
knit - b37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - b32 3
knit - b29 3
knit - b28 3
knit - b26 3
knit - f25 3
knit - f24 3
knit - b23 3
knit - f22 3
knit - b20 3
knit - b19 3
knit - b17 3
knit - b16 3
knit - f15 3
knit - b14 3
knit - f11 3
knit - b10 3
miss - f9 3
x-roller-advance 100
;pass: 22 
knit + b9 1
knit + f11 1
knit + f12 1
knit + f13 1
knit + b15 1
knit + f18 1
knit + b21 1
knit + b24 1
knit + f25 1
knit + f26 1
knit + b27 1
knit + b30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + b35 1
knit + b36 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + b41 1
miss + f42 1
;pass: 23 
knit - b40 2
knit - b39 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - b34 2
knit - b33 2
knit - b31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - b25 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - b18 2
knit - b16 2
knit - f15 2
knit - b13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - f9 2
miss - f8 2
;pass: 24 
knit + f10 3
knit + b11 3
knit + f14 3
knit + f16 3
knit + f17 3
knit + b19 3
knit + b20 3
knit + b22 3
knit + f23 3
knit + f24 3
knit + b26 3
knit + b28 3
knit + b29 3
knit + b32 3
knit + f34 3
knit + b35 3
knit + b37 3
knit + b38 3
knit + f41 3
miss + f42 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
;pass: 25 
knit + b42 1
knit - b41 1
knit - f40 1
knit - b39 1
knit - b36 1
knit - f33 1
knit - b30 1
knit - b27 1
knit - f26 1
knit - b24 1
knit - b23 1
knit - b21 1
knit - f19 1
knit - f18 1
knit - b17 1
knit - b15 1
knit - b14 1
knit - f12 1
knit - f11 1
knit - b9 1
miss - f8 1
x-roller-advance 100
x-roller-advance 50
;pass: 26 
knit - f8 2
knit + f9 2
knit + f10 2
knit + b12 2
knit + b13 2
knit + f15 2
knit + f16 2
knit + b18 2
knit + b19 2
knit + b22 2
knit + f24 2
knit + f25 2
knit + f27 2
knit + b28 2
knit + f30 2
knit + b31 2
knit + b33 2
knit + f34 2
knit + f37 2
knit + b40 2
knit + f41 2
miss + f42 2
x-roller-advance 100
x-roller-advance 50
x-roller-advance 50
;pass: 27 
knit + f42 3
knit - b41 3
knit - f39 3
knit - f38 3
knit - b37 3
knit - f36 3
knit - f35 3
knit - b34 3
knit - f32 3
knit - f31 3
knit - f29 3
knit - f28 3
knit - b26 3
knit - b25 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f17 3
knit - b16 3
knit - f14 3
knit - f13 3
knit - b11 3
knit - b10 3
miss - b8 3
knit + b8 3
x-roller-advance 100
x-roller-advance 100
;pass: 28 
knit + b9 1
knit + b12 1
knit + f14 1
knit + b15 1
knit + b17 1
knit + b18 1
knit + b20 1
knit + f21 1
knit + b23 1
knit + b24 1
knit + b27 1
knit + b29 1
knit + b30 1
knit + f32 1
knit + f33 1
knit + b35 1
knit + b36 1
knit + b38 1
knit + f39 1
knit + f40 1
knit + b42 1
miss + f43 1
;pass: 29 
knit - f42 2
knit - f41 2
knit - b40 2
knit - b39 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - b33 2
knit - b32 2
knit - b31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - f22 2
knit - b21 2
knit - b19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - b14 2
knit - b13 2
knit - f10 2
knit - f9 2
miss - f8 2
miss - f7 2
;pass: 30 
knit + f8 3
knit + b10 3
knit + f11 3
knit + f12 3
knit + f13 3
knit + b14 3
knit + b16 3
knit + b17 3
knit + f19 3
knit + f20 3
knit + b22 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + b28 3
knit + b29 3
knit + f31 3
knit + b32 3
knit + b34 3
knit + b35 3
knit + b37 3
knit + f38 3
knit + b41 3
miss + f42 3
miss + f43 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
;pass: 31 
knit - b42 1
knit - f39 1
knit - f38 1
knit - b36 1
knit - b33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - b27 1
knit - b24 1
knit - f21 1
knit - f20 1
knit - b18 1
knit - b15 1
knit - f14 1
knit - f13 1
knit - b12 1
knit - b11 1
knit - b9 1
knit - f8 1
miss - f7 1
knit + f7 1
x-roller-advance 100
x-roller-advance 50
x-roller-advance 50
;pass: 32 
knit - b7 2
knit + b8 2
knit + f10 2
knit + b13 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + b19 2
knit + b20 2
knit + b21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f28 2
knit + f29 2
knit + b31 2
knit + b34 2
knit + f35 2
knit + f36 2
knit + b37 2
knit + b38 2
knit + b39 2
knit + b40 2
knit + f42 2
miss + f43 2
knit - f43 2
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
;pass: 33 
knit + b43 3
knit - f41 3
knit - f40 3
knit - b38 3
knit - f37 3
knit - b35 3
knit - f34 3
knit - f33 3
knit - b32 3
knit - f30 3
knit - b29 3
knit - b28 3
knit - f27 3
knit - f26 3
knit - b25 3
knit - b23 3
knit - b22 3
knit - b20 3
knit - f19 3
knit - f18 3
knit - b17 3
knit - b16 3
knit - b14 3
knit - f12 3
knit - f11 3
knit - b10 3
knit - f9 3
knit - b8 3
miss - f7 3
x-roller-advance 100
;pass: 34 
knit + b9 1
knit + b11 1
knit + f12 1
knit + f13 1
knit + b15 1
knit + b18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f22 1
knit + b24 1
knit + b26 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + b33 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + b39 1
knit + b41 1
knit + b42 1
miss + f43 1
miss + f44 1
;pass: 35 
knit - f43 2
knit - f42 2
knit - b40 2
knit - f39 2
knit - b37 2
knit - b36 2
knit - b34 2
knit - f32 2
knit - b31 2
knit - b30 2
knit - b28 2
knit - b27 2
knit - f25 2
knit - f24 2
knit - b22 2
knit - b21 2
knit - b19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - b13 2
knit - b12 2
knit - f11 2
knit - b10 2
knit - b7 2
miss - f6 2
;pass: 36 
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + b11 3
knit + b14 3
knit + b16 3
knit + b17 3
knit + b20 3
knit + f23 3
knit + b25 3
knit + f26 3
knit + b29 3
knit + b32 3
knit + f33 3
knit + f34 3
knit + b35 3
knit + f38 3
knit + f40 3
knit + f41 3
knit + b43 3
miss + f44 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
x-roller-advance 50
;pass: 37 
knit + b44 1
knit - b42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - f37 1
knit - b36 1
knit - b33 1
knit - f30 1
knit - b27 1
knit - b26 1
knit - b24 1
knit - f23 1
knit - f22 1
knit - b21 1
knit - f19 1
knit - b18 1
knit - b15 1
knit - f12 1
knit - b9 1
knit - b8 1
miss - b6 1
knit + b6 1
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
;pass: 38 
knit - f6 2
knit + f7 2
knit + f10 2
knit + f11 2
knit + b12 2
knit + f13 2
knit + f14 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + b19 2
knit + f20 2
knit + f21 2
knit + b22 2
knit + b23 2
knit + f25 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + b30 2
knit + b31 2
knit + b34 2
knit + f35 2
knit + f36 2
knit + b37 2
knit + b40 2
knit + b41 2
knit + f42 2
knit + f43 2
miss + f44 2
x-roller-advance 100
x-roller-advance 50
;pass: 39 
knit + f44 3
knit - b43 3
knit - b41 3
knit - f39 3
knit - f38 3
knit - b35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - b29 3
knit - b28 3
knit - f26 3
knit - b25 3
knit - f24 3
knit - b23 3
knit - b20 3
knit - b17 3
knit - b16 3
knit - f15 3
knit - b14 3
knit - b13 3
knit - b11 3
knit - b10 3
knit - f9 3
knit - f8 3
knit - b7 3
miss - f6 3
x-roller-advance 100
;pass: 40 
knit + b6 1
knit + b8 1
knit + f9 1
knit + b12 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + b18 1
knit + b21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + b26 1
knit + b27 1
knit + b30 1
knit + f32 1
knit + b33 1
knit + b36 1
knit + b38 1
knit + b39 1
knit + f40 1
knit + f41 1
knit + b42 1
knit + b44 1
miss + f45 1
;pass: 41 
knit - f43 2
knit - f42 2
knit - b40 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - b32 2
knit - b31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - b24 2
knit - b22 2
knit - f19 2
knit - f18 2
knit - b16 2
knit - b15 2
knit - b13 2
knit - f12 2
knit - f11 2
knit - b10 2
knit - b9 2
knit - f7 2
miss - f6 2
miss - f5 2
;pass: 42 
knit + f6 3
knit + b7 3
knit + f8 3
knit + f10 3
knit + b11 3
knit + f13 3
knit + f14 3
knit + b17 3
knit + b19 3
knit + f20 3
knit + f21 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + b28 3
knit + b29 3
knit + f31 3
knit + b32 3
knit + b34 3
knit + b35 3
knit + b37 3
knit + f38 3
knit + f39 3
knit + b41 3
knit + b43 3
knit + f44 3
miss + f45 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
x-roller-advance 50
;pass: 43 
knit + b45 1
knit - b44 1
knit - b42 1
knit - f40 1
knit - f39 1
knit - b38 1
knit - b36 1
knit - b33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - b27 1
knit - f25 1
knit - f24 1
knit - f23 1
knit - b21 1
knit - b20 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - b14 1
knit - b12 1
knit - f10 1
knit - f9 1
knit - f8 1
knit - b6 1
miss - b5 1
knit + b5 1
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
;pass: 44 
knit - f5 2
knit + f6 2
knit + f7 2
knit + b8 2
knit + b9 2
knit + b10 2
knit + f11 2
knit + f12 2
knit + b13 2
knit + f14 2
knit + b15 2
knit + b16 2
knit + b18 2
knit + b19 2
knit + f21 2
knit + f22 2
knit + b24 2
knit + b25 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + b31 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + b39 2
knit + b40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
miss + f45 2
x-roller-advance 100
x-roller-advance 50
;pass: 45 
knit + f45 3
knit - b44 3
knit - b43 3
knit - b41 3
knit - f38 3
knit - b37 3
knit - b35 3
knit - b34 3
knit - b32 3
knit - b29 3
knit - b28 3
knit - f27 3
knit - f26 3
knit - b23 3
knit - b22 3
knit - f20 3
knit - f19 3
knit - b17 3
knit - b14 3
knit - f13 3
knit - b11 3
knit - b8 3
knit - b7 3
knit - b5 3
x-roller-advance 100
;pass: 46 
knit + b6 1
knit + f7 1
knit + f8 1
knit + f9 1
knit + b12 1
knit + f14 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + b20 1
knit + b21 1
knit + f24 1
knit + f25 1
knit + b26 1
knit + b27 1
knit + b30 1
knit + f31 1
knit + f32 1
knit + b33 1
knit + b36 1
knit + b38 1
knit + f39 1
knit + b42 1
knit + b45 1
miss + f46 1
;pass: 47 
knit - f44 2
knit - b43 2
knit - f42 2
knit - f41 2
knit - f40 2
knit - b39 2
knit - f37 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - b31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - b25 2
knit - b24 2
knit - f22 2
knit - f21 2
knit - f20 2
knit - b19 2
knit - b18 2
knit - b16 2
knit - b15 2
knit - f13 2
knit - f12 2
knit - b10 2
knit - b9 2
knit - b7 2
knit - f6 2
knit - f5 2
miss - f4 2
;pass: 48 
knit + b5 3
knit + b8 3
knit + f10 3
knit + f11 3
knit + b13 3
knit + b14 3
knit + b17 3
knit + f19 3
knit + b20 3
knit + b22 3
knit + f23 3
knit + f26 3
knit + b28 3
knit + b29 3
knit + b32 3
knit + b34 3
knit + b35 3
knit + f36 3
knit + b37 3
knit + f38 3
knit + b40 3
knit + b41 3
knit + f43 3
knit + b44 3
knit + f45 3
miss + f46 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
;pass: 49 
knit - b45 1
knit - b42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - b38 1
knit - b36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - f27 1
knit - f26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - f21 1
knit - f18 1
knit - f17 1
knit - b15 1
knit - f14 1
knit - b12 1
knit - f11 1
knit - b9 1
knit - f7 1
knit - b6 1
miss - f4 1
knit + f4 1
x-roller-advance 100
x-roller-advance 50
x-roller-advance 50
;pass: 50 
knit - b4 2
knit + f5 2
knit + f6 2
knit + b7 2
knit + f8 2
knit + b10 2
knit + b11 2
knit + f12 2
knit + f13 2
knit + b16 2
knit + b18 2
knit + f19 2
knit + f20 2
knit + b21 2
knit + f22 2
knit + b24 2
knit + b25 2
knit + b26 2
knit + b27 2
knit + b28 2
knit + f29 2
knit + b31 2
knit + b33 2
knit + b34 2
knit + b37 2
knit + b39 2
knit + b40 2
knit + f42 2
knit + b43 2
knit + f45 2
miss + f46 2
knit - f46 2
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
;pass: 51 
knit + b46 3
knit - f44 3
knit - f43 3
knit - b41 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - b32 3
knit - f30 3
knit - b29 3
knit - f28 3
knit - b26 3
knit - f23 3
knit - b22 3
knit - b20 3
knit - b19 3
knit - b17 3
knit - f16 3
knit - f15 3
knit - b14 3
knit - b13 3
knit - b11 3
knit - f10 3
knit - f9 3
knit - b8 3
knit - b5 3
miss - f4 3
x-roller-advance 100
;pass: 52 
knit + f4 1
knit + f5 1
knit + b6 1
knit + b9 1
knit + f11 1
knit + f12 1
knit + b15 1
knit + b18 1
knit + f19 1
knit + f20 1
knit + f21 1
knit + f23 1
knit + f24 1
knit + f26 1
knit + f27 1
knit + f30 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit + b39 1
knit + f41 1
knit + b42 1
knit + b44 1
knit + b45 1
miss + f46 1
miss + f47 1
;pass: 53 
knit - f46 2
knit - f45 2
knit - f44 2
knit - b43 2
knit - b40 2
knit - f39 2
knit - b37 2
knit - b34 2
knit - b33 2
knit - f32 2
knit - b31 2
knit - b30 2
knit - b28 2
knit - b27 2
knit - f25 2
knit - b24 2
knit - b23 2
knit - b22 2
knit - b21 2
knit - b19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - b13 2
knit - b12 2
knit - f10 2
knit - f8 2
knit - b7 2
knit - b4 2
miss - f3 2
;pass: 54 
knit + b5 3
knit + f6 3
knit + f7 3
knit + b8 3
knit + f9 3
knit + b10 3
knit + b11 3
knit + f13 3
knit + f14 3
knit + b16 3
knit + b17 3
knit + b20 3
knit + f22 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + f28 3
knit + f29 3
knit + f31 3
knit + b32 3
knit + f35 3
knit + f36 3
knit + f38 3
knit + f40 3
knit + b41 3
knit + f42 3
knit + f43 3
knit + b44 3
knit + b46 3
miss + f47 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
x-roller-advance 50
;pass: 55 
knit + b47 1
knit - b45 1
knit - b42 1
knit - b39 1
knit - b38 1
knit - f37 1
knit - f36 1
knit - b35 1
knit - b33 1
knit - f30 1
knit - f29 1
knit - b27 1
knit - b24 1
knit - f23 1
knit - f22 1
knit - b21 1
knit - b18 1
knit - b15 1
knit - b14 1
knit - f12 1
knit - b9 1
knit - b6 1
knit - f5 1
miss - b3 1
knit + b3 1
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
;pass: 56 
knit + b4 2
knit + b7 2
knit + f8 2
knit + f9 2
knit + b10 2
knit + b12 2
knit + b13 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + b22 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + b28 2
knit + b29 2
knit + b30 2
knit + f31 2
knit + f32 2
knit + f33 2
knit + b34 2
knit + b36 2
knit + b37 2
knit + f38 2
knit + b40 2
knit + f41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + f46 2
miss + f47 2
knit - f47 2
x-roller-advance 100
x-roller-advance 50
;pass: 57 
knit - b47 3
knit - b46 3
knit - b44 3
knit - b43 3
knit - b41 3
knit - f40 3
knit - f39 3
knit - b38 3
knit - f35 3
knit - f34 3
knit - b32 3
knit - b31 3
knit - b29 3
knit - f28 3
knit - f27 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - f21 3
knit - f20 3
knit - b19 3
knit - b17 3
knit - b16 3
knit - f14 3
knit - f13 3
knit - f11 3
knit - f10 3
knit - b8 3
knit - f7 3
knit - f6 3
knit - b5 3
knit - f4 3
miss - f3 3
knit + f3 3
x-roller-advance 100
;pass: 58 
knit + b3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + b9 1
knit + f11 1
knit + f12 1
knit + b14 1
knit + b15 1
knit + b18 1
knit + b20 1
knit + f21 1
knit + f22 1
knit + b24 1
knit + b27 1
knit + f28 1
knit + f29 1
knit + b30 1
knit + b33 1
knit + f35 1
knit + f36 1
knit + b39 1
knit + f40 1
knit + f41 1
knit + b42 1
knit + b45 1
miss + f47 1
miss + f48 1
;pass: 59 
knit - f47 2
knit - f46 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - b40 2
knit - f37 2
knit - b36 2
knit - b35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - b28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - b22 2
knit - b21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - f17 2
knit - b16 2
knit - b13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - b7 2
knit - b4 2
miss - f2 2
;pass: 60 
knit + f3 3
knit + b5 3
knit + f6 3
knit + f7 3
knit + f8 3
knit + f9 3
knit + f10 3
knit + b11 3
knit + f13 3
knit + f14 3
knit + f15 3
knit + f16 3
knit + b17 3
knit + b19 3
knit + b20 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + b29 3
knit + b31 3
knit + b32 3
knit + b34 3
knit + b35 3
knit + b37 3
knit + f38 3
knit + f39 3
knit + b41 3
knit + b43 3
knit + b44 3
knit + f45 3
knit + b46 3
knit + b47 3
miss + f48 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
x-roller-advance 50
x-roller-advance 50
;pass: 61 
knit + f48 1
knit - b45 1
knit - b42 1
knit - f41 1
knit - f40 1
knit - b39 1
knit - b38 1
knit - b36 1
knit - f35 1
knit - f34 1
knit - b33 1
knit - b30 1
knit - f28 1
knit - f27 1
knit - b24 1
knit - f21 1
knit - f20 1
knit - b18 1
knit - b15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - b9 1
knit - b8 1
knit - f6 1
knit - f5 1
knit - b3 1
miss - b2 1
knit + b2 1
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
x-roller-advance 50
;pass: 62 
knit - f2 2
knit + f3 2
knit + b4 2
knit + b6 2
knit + b7 2
knit + f9 2
knit + f10 2
knit + b12 2
knit + b13 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + b19 2
knit + b21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + b27 2
knit + b28 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + b34 2
knit + f36 2
knit + b37 2
knit + f38 2
knit + f39 2
knit + b40 2
knit + f43 2
knit + f45 2
knit + f46 2
miss + b48 2
knit - b48 2
x-roller-advance 100
x-roller-advance 100
;pass: 63 
knit - f47 3
knit - b46 3
knit - f44 3
knit - b43 3
knit - f42 3
knit - b41 3
knit - b38 3
knit - f37 3
knit - b35 3
knit - f33 3
knit - b32 3
knit - b31 3
knit - f29 3
knit - f26 3
knit - b25 3
knit - b23 3
knit - b22 3
knit - b20 3
knit - f19 3
knit - b17 3
knit - b16 3
knit - f15 3
knit - f14 3
knit - f11 3
knit - b10 3
knit - f8 3
knit - f7 3
knit - b5 3
knit - f4 3
knit - b2 3
;pass: 64 
knit + b3 1
knit + f6 1
knit + b8 1
knit + b9 1
knit + b11 1
knit + b12 1
knit + f13 1
knit + b14 1
knit + b15 1
knit + b18 1
knit + f19 1
knit + f20 1
knit + b21 1
knit + b24 1
knit + f26 1
knit + b27 1
knit + f28 1
knit + b29 1
knit + b30 1
knit + f33 1
knit + b36 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + f42 1
knit + b44 1
knit + b45 1
knit + f46 1
knit + f47 1
knit + f48 1
miss + f49 1
;pass: 65 
knit - b48 2
knit - b47 2
knit - b46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - b42 2
knit - b40 2
knit - b39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - b34 2
knit - b33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - b28 2
knit - b26 2
knit - f25 2
knit - f24 2
knit - f22 2
knit - b19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - b13 2
knit - b10 2
knit - f9 2
knit - f8 2
knit - b7 2
knit - b6 2
knit - b4 2
knit - f3 2
knit - f2 2
miss - f1 2
;pass: 66 
knit + b2 3
knit + f4 3
knit + f5 3
knit + f7 3
knit + b8 3
knit + f10 3
knit + f11 3
knit + f12 3
knit + f14 3
knit + b16 3
knit + b17 3
knit + b20 3
knit + f21 3
knit + b22 3
knit + f23 3
knit + b25 3
knit + b26 3
knit + f27 3
knit + f29 3
knit + b31 3
knit + b32 3
knit + f34 3
knit + f35 3
knit + b37 3
knit + b38 3
knit + b41 3
knit + b43 3
knit + b44 3
knit + b47 3
miss + f48 3
miss + f49 3
x-speed-number 100
;inc 1 on left
;inc 1 on right
rack 0
x-speed-number 100
;pass: 67 
knit - b48 1
knit - f46 1
knit - b45 1
knit - b42 1
knit - f39 1
knit - b36 1
knit - b35 1
knit - f33 1
knit - f30 1
knit - b29 1
knit - b27 1
knit - b24 1
knit - f23 1
knit - b21 1
knit - f20 1
knit - f19 1
knit - b18 1
knit - b15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - b9 1
knit - f6 1
knit - f5 1
knit - f4 1
knit - b3 1
miss - f1 1
x-roller-advance 50
x-roller-advance 50
;pass: 68 
knit - f1 2
knit + f2 2
knit + f3 2
knit + b4 2
knit + b5 2
knit + b6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + f10 2
knit + b11 2
knit + b12 2
knit + b13 2
knit + f14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + b19 2
knit + b22 2
knit + b23 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + b28 2
knit + b30 2
knit + f31 2
knit + f32 2
knit + b33 2
knit + f34 2
knit + f37 2
knit + f38 2
knit + b39 2
knit + b40 2
knit + b43 2
knit + f44 2
knit + f45 2
knit + b46 2
knit + f47 2
miss + b49 2
knit - b49 2
x-roller-advance 100
x-roller-advance 100
x-roller-advance 50
x-roller-advance 50
;pass: 69 
knit + f49 3
knit - f48 3
knit - b47 3
knit - b44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f40 3
knit - b38 3
knit - b37 3
knit - f36 3
knit - f35 3
knit - b34 3
knit - b32 3
knit - b31 3
knit - f29 3
knit - f28 3
knit - b26 3
knit - b25 3
knit - f24 3
knit - b23 3
knit - f22 3
knit - f21 3
knit - b20 3
knit - f18 3
knit - b17 3
knit - b16 3
knit - b14 3
knit - b11 3
knit - b10 3
knit - b8 3
knit - b7 3
knit - b5 3
knit - b2 3
miss - b1 3
knit + b1 3
x-roller-advance 100
x-roller-advance 100
;pass: 70 
knit + b3 1
knit + f4 1
knit + f5 1
knit + f6 1
knit + b9 1
knit + f12 1
knit + f13 1
knit + b15 1
knit + f17 1
knit + b18 1
knit + f20 1
knit + b21 1
knit + f23 1
knit + f24 1
knit + b27 1
knit + b29 1
knit + f30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + b35 1
knit + b36 1
knit + b39 1
knit + b41 1
knit + b42 1
knit + b45 1
knit + b48 1
miss + f49 1
;pass: 71 
knit - b49 2
knit - f46 2
knit - f45 2
knit - f44 2
knit - f43 2
knit - b40 2
knit - f39 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - b34 2
knit - b33 2
knit - b31 2
knit - b30 2
knit - f29 2
knit - b28 2
knit - f26 2
knit - f25 2
knit - b24 2
knit - b22 2
knit - b19 2
knit - f18 2
knit - f16 2
knit - f15 2
knit - f14 2
knit - b13 2
knit - b12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - b7 2
knit - b6 2
knit - b4 2
knit - f3 2
knit - f2 2
knit - f1 2
;pass: 72 
knit + b1 3
knit + b2 3
knit + b5 3
knit + f7 3
knit + b8 3
knit + b10 3
knit + b11 3
knit + b14 3
knit + b16 3
knit + b17 3
knit + f19 3
knit + b20 3
knit + f21 3
knit + f22 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + f27 3
knit + f28 3
knit + b29 3
knit + b32 3
knit + f34 3
knit + f35 3
knit + b37 3
knit + b38 3
knit + f40 3
knit + f41 3
knit + f42 3
knit + b43 3
knit + b44 3
knit + b46 3
knit + f47 3
knit + f48 3
knit + f49 3
x-speed-number 100
;inc 1 on right
rack 1
xfer b49 f50
rack 0
x-add-roller-advance -100
miss - f49 3
xfer f49 b49
xfer f50 b50
rack 1
xfer b49 f50
rack 0
x-speed-number 100
x-roller-advance 50
;pass: 73 ;-;1
knit + f49 1
knit - b48 1
knit - b47 1
knit - b45 1
knit - f42 1
knit - f41 1
knit - b39 1
knit - b36 1
knit - f35 1
knit - f34 1
knit - b33 1
knit - f32 1
knit - f31 1
knit - f30 1
knit - f28 1
knit - b27 1
knit - f24 1
knit - f23 1
knit - b21 1
knit - b18 1
knit - f17 1
knit - f16 1
knit - b15 1
knit - b12 1
knit - b9 1
knit - f8 1
knit - b6 1
knit - f4 1
knit - b3 1
knit - f1 1
x-roller-advance 100
x-roller-advance 50
;pass: 74 ;+;2
knit + b1 2
knit + f2 2
knit + b4 2
knit + b7 2
knit + f9 2
knit + b10 2
knit + f12 2
knit + f13 2
knit + b16 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + b22 2
knit + b24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + b28 2
knit + b30 2
knit + b31 2
knit + b34 2
knit + b35 2
knit + f36 2
knit + b37 2
knit + f38 2
knit + f39 2
knit + b40 2
knit + b41 2
knit + b42 2
knit + b43 2
knit + f45 2
knit + f46 2
miss + b49 2
knit - b49 2
miss + f50 2
x-roller-advance 100
;pass: 75 ;-;3
knit - f50 3
knit - f48 3
knit - f47 3
knit - b46 3
knit - f44 3
knit - f43 3
knit - b41 3
knit - f40 3
knit - b38 3
knit - f37 3
knit - b35 3
knit - f33 3
knit - b32 3
knit - f29 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - f22 3
knit - b20 3
knit - b19 3
knit - f18 3
knit - b17 3
knit - f15 3
knit - f14 3
knit - b13 3
knit - f11 3
knit - f10 3
knit - b8 3
knit - f7 3
knit - f6 3
knit - f5 3
knit - f3 3
knit - b2 3
miss - f1 3
;pass: 76 ;+;1
knit + f2 1
knit + f3 1
knit + b5 1
knit + b6 1
knit + f9 1
knit + f10 1
knit + b11 1
knit + b12 1
knit + b14 1
knit + f15 1
knit + f16 1
knit + b18 1
knit + b21 1
knit + f22 1
knit + f23 1
knit + b24 1
knit + b27 1
knit + f29 1
knit + f30 1
knit + f33 1
knit + f34 1
knit + b36 1
knit + b39 1
knit + f40 1
knit + f41 1
knit + b42 1
knit + f44 1
knit + b45 1
knit + b47 1
knit + b48 1
knit + b50 1
;pass: 77 ;-;2
knit - b49 2
knit - f48 2
knit - f47 2
knit - f46 2
knit - f45 2
knit - b44 2
knit - b43 2
knit - b40 2
knit - f38 2
knit - f37 2
knit - f36 2
knit - b34 2
knit - b33 2
knit - b31 2
knit - b30 2
knit - b29 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - b25 2
knit - b22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - b16 2
knit - b15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - b10 2
knit - b9 2
knit - f8 2
knit - f7 2
knit - b4 2
knit - b3 2
knit - f1 2
;pass: 78 ;+;3
knit + b1 3
knit + b2 3
knit + f4 3
knit + f5 3
knit + f6 3
knit + b7 3
knit + b8 3
knit + f11 3
knit + b13 3
knit + b14 3
knit + f17 3
knit + f18 3
knit + b19 3
knit + b20 3
knit + b23 3
knit + f24 3
knit + f25 3
knit + b26 3
knit + b28 3
knit + b29 3
knit + f31 3
knit + f32 3
knit + f35 3
knit + b37 3
knit + b38 3
knit + f39 3
knit + b41 3
knit + f42 3
knit + f43 3
knit + b44 3
knit + b46 3
knit + b47 3
knit + f49 3
knit + f50 3
x-speed-number 100
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b50 f49
xfer b49 f48
rack 1
x-add-roller-advance 100
xfer f50 b49
rack 0
x-speed-number 100
;pass: 79 
knit - b48 1
knit - f45 1
knit - f44 1
knit - b42 1
knit - f39 1
knit - f37 1
knit - b36 1
knit - b35 1
knit - b33 1
knit - b32 1
knit - b30 1
knit - b27 1
knit - f26 1
knit - b24 1
knit - b21 1
knit - f19 1
knit - b18 1
knit - b17 1
knit - b15 1
knit - f12 1
knit - b11 1
knit - b9 1
knit - b6 1
knit - b5 1
knit - b3 1
miss - f1 1
;pass: 80 
knit + f1 2
knit + f2 2
knit + b4 2
knit + f5 2
knit + f6 2
knit + f7 2
knit + f8 2
knit + f9 2
knit + b10 2
knit + b12 2
knit + f13 2
knit + f14 2
knit + b16 2
knit + b19 2
knit + f20 2
knit + f21 2
knit + b22 2
knit + b25 2
knit + f27 2
knit + f28 2
knit + b31 2
knit + f34 2
knit + b37 2
knit + f38 2
knit + b39 2
knit + b40 2
knit + f41 2
knit + b43 2
knit + b45 2
knit + b46 2
knit + f47 2
knit + f48 2
knit + b49 2
;pass: 81 
knit - f49 3
knit - b47 3
knit - f46 3
knit - b44 3
knit - f43 3
knit - f42 3
knit - b41 3
knit - f40 3
knit - b38 3
knit - f36 3
knit - f35 3
knit - b34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - b28 3
knit - b26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - b20 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - b14 3
knit - b13 3
knit - f11 3
knit - f10 3
knit - b8 3
knit - b7 3
knit - b5 3
knit - f4 3
knit - f3 3
knit - b2 3
knit - b1 3
;pass: 82 
knit + f2 1
knit + b3 1
knit + b6 1
knit + f9 1
knit + f11 1
knit + f12 1
knit + b15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + b21 1
knit + b23 1
knit + b24 1
knit + f25 1
knit + f26 1
knit + b27 1
knit + b29 1
knit + b30 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + b35 1
knit + b36 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + f41 1
knit + b42 1
knit + f45 1
knit + f46 1
knit + f47 1
knit + f48 1
miss + f49 1
;pass: 83 
knit - b49 2
knit - b48 2
knit - b46 2
knit - b45 2
knit - f44 2
knit - f43 2
knit - f42 2
knit - b40 2
knit - b39 2
knit - f37 2
knit - f36 2
knit - f35 2
knit - b34 2
knit - b33 2
knit - b32 2
knit - b31 2
knit - f28 2
knit - f27 2
knit - b25 2
knit - b22 2
knit - f21 2
knit - f20 2
knit - b19 2
knit - b18 2
knit - b17 2
knit - b16 2
knit - f14 2
knit - f13 2
knit - b12 2
knit - b11 2
knit - b10 2
knit - b9 2
knit - f7 2
knit - f6 2
knit - f5 2
knit - f4 2
knit - b1 2
;pass: 84 
knit + f1 3
knit + b2 3
knit + f3 3
knit + b4 3
knit + b5 3
knit + b7 3
knit + f8 3
knit + f10 3
knit + b11 3
knit + b13 3
knit + b14 3
knit + f15 3
knit + b17 3
knit + b20 3
knit + f22 3
knit + f23 3
knit + f24 3
knit + b26 3
knit + b28 3
knit + f29 3
knit + f30 3
knit + f31 3
knit + b32 3
knit + b35 3
knit + b37 3
knit + b38 3
knit + b41 3
knit + b43 3
knit + b44 3
knit + b47 3
knit + f49 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b1 f2
xfer b2 f3
rack -1
x-add-roller-advance 100
xfer f1 b2
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b49 f48
xfer b48 f47
rack 1
x-add-roller-advance 100
xfer f49 b48
rack 0
x-speed-number 100
;pass: 85 
knit - f48 1
knit - f47 1
knit - f46 1
knit - b45 1
knit - b42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - b36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - b30 1
knit - b29 1
knit - b27 1
knit - f24 1
knit - f23 1
knit - b21 1
knit - f18 1
knit - f17 1
knit - f16 1
knit - b15 1
knit - b12 1
knit - f11 1
knit - f10 1
knit - f9 1
knit - b8 1
knit - b6 1
knit - f3 1
knit - f2 1
;pass: 86 
knit + b3 2
knit + b4 2
knit + f5 2
knit + f6 2
knit + b7 2
knit + b9 2
knit + b10 2
knit + f12 2
knit + f13 2
knit + b16 2
knit + b18 2
knit + f19 2
knit + f20 2
knit + b22 2
knit + b23 2
knit + b24 2
knit + f25 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + f31 2
knit + b33 2
knit + b34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f38 2
knit + b39 2
knit + b40 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + f45 2
knit + b46 2
knit + b48 2
;pass: 87 
knit - b47 3
knit - b44 3
knit - b43 3
knit - b41 3
knit - b38 3
knit - b37 3
knit - b35 3
knit - b32 3
knit - b31 3
knit - b29 3
knit - b28 3
knit - f27 3
knit - f26 3
knit - b25 3
knit - b23 3
knit - f22 3
knit - f21 3
knit - b20 3
knit - b19 3
knit - b17 3
knit - f15 3
knit - f14 3
knit - b13 3
knit - b11 3
knit - f8 3
knit - f7 3
knit - b5 3
knit - f4 3
knit - b2 3
;pass: 88 
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + b8 1
knit + b9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + b14 1
knit + b15 1
knit + f17 1
knit + f18 1
knit + b21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + b26 1
knit + b27 1
knit + f28 1
knit + b30 1
knit + f31 1
knit + f32 1
knit + b33 1
knit + f34 1
knit + f35 1
knit + b36 1
knit + f38 1
knit + f39 1
knit + f42 1
knit + f45 1
knit + f46 1
knit + f48 1
;pass: 89 
knit - b48 2
knit - f47 2
knit - b46 2
knit - b45 2
knit - f44 2
knit - b43 2
knit - b42 2
knit - f41 2
knit - b40 2
knit - b39 2
knit - f37 2
knit - b34 2
knit - b31 2
knit - f30 2
knit - f29 2
knit - b28 2
knit - b25 2
knit - b24 2
knit - b22 2
knit - b19 2
knit - b18 2
knit - b16 2
knit - f15 2
knit - b13 2
knit - b12 2
knit - b10 2
knit - f8 2
knit - b7 2
knit - b4 2
knit - b3 2
miss - f2 2
;pass: 90 
knit + f2 3
knit + b5 3
knit + f6 3
knit + f7 3
knit + b8 3
knit + f9 3
knit + b11 3
knit + f13 3
knit + f14 3
knit + f16 3
knit + b17 3
knit + f19 3
knit + f20 3
knit + f21 3
knit + b23 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + b29 3
knit + b32 3
knit + f33 3
knit + b35 3
knit + f36 3
knit + b37 3
knit + b38 3
knit + f40 3
knit + b41 3
knit + f43 3
knit + b44 3
knit + b47 3
miss + f48 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b2 f3
xfer b3 f4
rack -1
x-add-roller-advance 100
xfer f2 b3
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b48 f47
xfer b47 f46
rack 1
x-add-roller-advance 100
xfer f48 b47
rack 0
x-speed-number 100
;pass: 91 
knit - f47 1
knit - b45 1
knit - b42 1
knit - b39 1
knit - f37 1
knit - b36 1
knit - f34 1
knit - b33 1
knit - b30 1
knit - f27 1
knit - b26 1
knit - f24 1
knit - b21 1
knit - f20 1
knit - f19 1
knit - f18 1
knit - b15 1
knit - b14 1
knit - f12 1
knit - f11 1
knit - b9 1
knit - b6 1
knit - f5 1
knit - f4 1
knit - b3 1
;pass: 92 
knit + f3 2
knit + b4 2
knit + f7 2
knit + f8 2
knit + f10 2
knit + b12 2
knit + b13 2
knit + f14 2
knit + b16 2
knit + f17 2
knit + b18 2
knit + b19 2
knit + b20 2
knit + f22 2
knit + f23 2
knit + b24 2
knit + b25 2
knit + f26 2
knit + b27 2
knit + b28 2
knit + b31 2
knit + f33 2
knit + b34 2
knit + b37 2
knit + f40 2
knit + f41 2
knit + f42 2
knit + b43 2
knit + f46 2
miss + f47 2
;pass: 93 
knit - b47 3
knit - b46 3
knit - f45 3
knit - f44 3
knit - f43 3
knit - b41 3
knit - b40 3
knit - f39 3
knit - f38 3
knit - f36 3
knit - f35 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - b26 3
knit - f25 3
knit - b23 3
knit - b22 3
knit - f21 3
knit - b20 3
knit - b17 3
knit - f16 3
knit - f15 3
knit - b14 3
knit - f13 3
knit - b11 3
knit - b10 3
knit - f9 3
knit - b8 3
knit - b7 3
knit - f6 3
knit - b5 3
miss - f3 3
;pass: 94 
knit + f3 1
knit + f4 1
knit + f5 1
knit + b6 1
knit + f8 1
knit + b9 1
knit + f10 1
knit + f11 1
knit + f12 1
knit + f15 1
knit + f17 1
knit + f18 1
knit + f19 1
knit + b21 1
knit + b24 1
knit + f26 1
knit + b27 1
knit + b29 1
knit + b30 1
knit + b32 1
knit + f33 1
knit + b35 1
knit + b36 1
knit + b38 1
knit + b39 1
knit + f40 1
knit + b42 1
knit + b44 1
knit + b45 1
knit + f47 1
;pass: 95 
knit - b46 2
knit - f45 2
knit - f44 2
knit - b43 2
knit - f42 2
knit - b40 2
knit - f38 2
knit - f37 2
knit - f35 2
knit - b34 2
knit - b33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f28 2
knit - f27 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - b22 2
knit - f21 2
knit - f20 2
knit - b19 2
knit - b18 2
knit - f16 2
knit - b15 2
knit - f14 2
knit - f13 2
knit - b12 2
knit - b10 2
knit - f9 2
knit - f7 2
knit - f6 2
knit - b4 2
knit - b3 2
;pass: 96 
knit + b5 3
knit + b7 3
knit + b8 3
knit + b11 3
knit + b13 3
knit + b14 3
knit + b16 3
knit + b17 3
knit + b20 3
knit + f22 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + b28 3
knit + f29 3
knit + b31 3
knit + b32 3
knit + f34 3
knit + b35 3
knit + f36 3
knit + b37 3
knit + b38 3
knit + f39 3
knit + f41 3
knit + f43 3
knit + b44 3
knit + f46 3
knit + b47 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b3 f4
xfer b4 f5
rack -1
x-add-roller-advance 100
xfer f3 b4
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b47 f46
xfer b46 f45
rack 1
x-add-roller-advance 100
xfer f47 b46
rack 0
x-speed-number 100
;pass: 97 
knit - f46 1
knit - f45 1
knit - b42 1
knit - f41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - b36 1
knit - f34 1
knit - f33 1
knit - f32 1
knit - b30 1
knit - b29 1
knit - b27 1
knit - f26 1
knit - b24 1
knit - f22 1
knit - f21 1
knit - b18 1
knit - f15 1
knit - f14 1
knit - b12 1
knit - b9 1
knit - f8 1
knit - f7 1
knit - b6 1
miss - f4 1
;pass: 98 
knit + f4 2
knit + f5 2
knit + b7 2
knit + f9 2
knit + f10 2
knit + f11 2
knit + f12 2
knit + b13 2
knit + b15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + f19 2
knit + b21 2
knit + b22 2
knit + f24 2
knit + f25 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + b31 2
knit + b33 2
knit + b34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + b39 2
knit + b40 2
knit + b41 2
knit + f42 2
knit + f43 2
knit + f44 2
knit + b45 2
knit + b46 2
;pass: 99 
knit - b44 3
knit - b43 3
knit - b41 3
knit - b38 3
knit - b37 3
knit - b35 3
knit - b32 3
knit - f31 3
knit - b29 3
knit - b28 3
knit - f27 3
knit - b26 3
knit - b25 3
knit - f23 3
knit - f20 3
knit - b19 3
knit - b17 3
knit - b16 3
knit - b14 3
knit - f13 3
knit - b11 3
knit - b10 3
knit - b8 3
knit - f6 3
knit - b5 3
knit - b4 3
;pass: 100 
knit + b6 1
knit + f7 1
knit + f8 1
knit + b9 1
knit + b12 1
knit + f13 1
knit + f14 1
knit + b15 1
knit + b18 1
knit + f20 1
knit + f21 1
knit + b23 1
knit + b24 1
knit + b27 1
knit + f28 1
knit + b30 1
knit + f31 1
knit + f32 1
knit + b33 1
knit + f34 1
knit + f35 1
knit + b36 1
knit + f38 1
knit + f39 1
knit + f41 1
knit + f42 1
knit + f45 1
miss + f46 1
;pass: 101 
knit - b46 2
knit - b45 2
knit - f44 2
knit - f43 2
knit - b42 2
knit - f40 2
knit - b39 2
knit - f37 2
knit - b34 2
knit - f33 2
knit - b31 2
knit - f30 2
knit - b28 2
knit - b25 2
knit - f23 2
knit - b22 2
knit - b21 2
knit - b20 2
knit - b19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - b13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - b7 2
knit - b4 2
;pass: 102 
knit + f4 3
knit + f5 3
knit + f6 3
knit + b8 3
knit + f9 3
knit + b10 3
knit + b11 3
knit + b14 3
knit + b16 3
knit + b17 3
knit + f19 3
knit + b20 3
knit + f22 3
knit + b23 3
knit + f24 3
knit + f25 3
knit + f26 3
knit + f27 3
knit + f29 3
knit + b32 3
knit + b35 3
knit + f36 3
knit + b37 3
knit + b38 3
knit + b40 3
knit + b41 3
knit + b43 3
knit + b44 3
knit + f46 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b4 f5
xfer b5 f6
rack -1
x-add-roller-advance 100
xfer f4 b5
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b46 f45
xfer b45 f44
rack 1
x-add-roller-advance 100
xfer f46 b45
rack 0
x-speed-number 100
;pass: 103 
knit - f45 1
knit - b42 1
knit - f40 1
knit - b39 1
knit - f38 1
knit - b36 1
knit - f35 1
knit - f34 1
knit - f33 1
knit - b30 1
knit - b29 1
knit - f28 1
knit - f27 1
knit - b26 1
knit - b24 1
knit - f21 1
knit - f20 1
knit - f19 1
knit - b18 1
knit - b15 1
knit - f13 1
knit - b12 1
knit - b9 1
knit - f6 1
knit - b5 1
;pass: 104 
knit + b6 2
knit + f7 2
knit + b10 2
knit + b13 2
knit + f14 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + b19 2
knit + b21 2
knit + b22 2
knit + f23 2
knit + f24 2
knit + b25 2
knit + b27 2
knit + b28 2
knit + f30 2
knit + f31 2
knit + f32 2
knit + b33 2
knit + b34 2
knit + b37 2
knit + b40 2
knit + b43 2
knit + b45 2
;pass: 105 
knit - f44 3
knit - f43 3
knit - f42 3
knit - f41 3
knit - f39 3
knit - b38 3
knit - f37 3
knit - f36 3
knit - b35 3
knit - b32 3
knit - b31 3
knit - f29 3
knit - f26 3
knit - f25 3
knit - b23 3
knit - f22 3
knit - b20 3
knit - b17 3
knit - b16 3
knit - f15 3
knit - b14 3
knit - f12 3
knit - f11 3
knit - f10 3
knit - f9 3
knit - f8 3
knit - b7 3
knit - f5 3
;pass: 106 
knit + b5 1
knit + f6 1
knit + b8 1
knit + b9 1
knit + b11 1
knit + b12 1
knit + f13 1
knit + b15 1
knit + b18 1
knit + f19 1
knit + f20 1
knit + b21 1
knit + b24 1
knit + f26 1
knit + f27 1
knit + b29 1
knit + b30 1
knit + f33 1
knit + f34 1
knit + b36 1
knit + f38 1
knit + f39 1
knit + f40 1
knit + b41 1
knit + b42 1
knit + b44 1
knit + f45 1
;pass: 107 
knit - b45 2
knit - f44 2
knit - f43 2
knit - b40 2
knit - b39 2
knit - f37 2
knit - f36 2
knit - b34 2
knit - b33 2
knit - f32 2
knit - f31 2
knit - f30 2
knit - f29 2
knit - f28 2
knit - b27 2
knit - b26 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - b22 2
knit - f21 2
knit - b19 2
knit - f18 2
knit - f17 2
knit - f16 2
knit - b13 2
knit - f12 2
knit - f11 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - f7 2
knit - b6 2
knit - f5 2
;pass: 108 
knit + b5 3
knit + b7 3
knit + b8 3
knit + b10 3
knit + b11 3
knit + f14 3
knit + f15 3
knit + b16 3
knit + b17 3
knit + b20 3
knit + f22 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + b28 3
knit + b29 3
knit + b31 3
knit + b32 3
knit + f35 3
knit + b37 3
knit + b38 3
knit + f41 3
knit + f42 3
knit + b43 3
knit + b44 3
miss + f45 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b5 f6
xfer b6 f7
rack -1
x-add-roller-advance 100
xfer f5 b6
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b45 f44
xfer b44 f43
rack 1
x-add-roller-advance 100
xfer f45 b44
rack 0
x-speed-number 100
;pass: 109 
knit - b42 1
knit - b41 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - b36 1
knit - b35 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - b27 1
knit - f26 1
knit - f25 1
knit - b24 1
knit - b21 1
knit - f19 1
knit - f18 1
knit - b15 1
knit - b14 1
knit - f13 1
knit - f12 1
knit - f11 1
knit - b9 1
knit - f6 1
;pass: 110 
knit + b6 2
knit + b7 2
knit + f8 2
knit + f9 2
knit + b10 2
knit + b12 2
knit + b13 2
knit + f15 2
knit + b16 2
knit + b18 2
knit + b19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + b25 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + b31 2
knit + b33 2
knit + b34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + b39 2
knit + b40 2
knit + f42 2
knit + f43 2
knit + f44 2
;pass: 111 
knit - b44 3
knit - b43 3
knit - f41 3
knit - b38 3
knit - b37 3
knit - b35 3
knit - f34 3
knit - b32 3
knit - b29 3
knit - b28 3
knit - b26 3
knit - f24 3
knit - f23 3
knit - b22 3
knit - b20 3
knit - f17 3
knit - f16 3
knit - f14 3
knit - b11 3
knit - f10 3
knit - b8 3
knit - f7 3
miss - f6 3
;pass: 112 
knit + b6 1
knit + b9 1
knit + f11 1
knit + f12 1
knit + b14 1
knit + b15 1
knit + b17 1
knit + f18 1
knit + f19 1
knit + b21 1
knit + b23 1
knit + b24 1
knit + f26 1
knit + b27 1
knit + b30 1
knit + f33 1
knit + b36 1
knit + b39 1
knit + f40 1
knit + b41 1
knit + b42 1
miss + f44 1
;pass: 113 
knit - f44 2
knit - b43 2
knit - f41 2
knit - b40 2
knit - f38 2
knit - f37 2
knit - f34 2
knit - b33 2
knit - f31 2
knit - f30 2
knit - b28 2
knit - f27 2
knit - f25 2
knit - f24 2
knit - b22 2
knit - b19 2
knit - b18 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - b13 2
knit - b12 2
knit - f10 2
knit - f9 2
knit - f8 2
knit - b7 2
miss - f6 2
;pass: 114 
knit + f6 3
knit + f7 3
knit + b8 3
knit + b10 3
knit + b11 3
knit + f13 3
knit + f14 3
knit + b16 3
knit + b17 3
knit + f20 3
knit + f21 3
knit + f22 3
knit + f23 3
knit + b25 3
knit + b26 3
knit + f28 3
knit + f29 3
knit + b31 3
knit + f32 3
knit + b34 3
knit + f35 3
knit + f36 3
knit + b37 3
knit + b38 3
knit + f39 3
knit + b41 3
knit + f42 3
knit + f43 3
knit + b44 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b6 f7
xfer b7 f8
rack -1
x-add-roller-advance 100
xfer f6 b7
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b44 f43
xfer b43 f42
rack 1
x-add-roller-advance 100
xfer f44 b43
rack 0
x-speed-number 100
;pass: 115 
knit - b42 1
knit - f40 1
knit - f39 1
knit - f38 1
knit - b36 1
knit - b35 1
knit - f33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - b29 1
knit - b27 1
knit - b24 1
knit - b23 1
knit - f21 1
knit - b20 1
knit - b18 1
knit - b15 1
knit - f14 1
knit - b12 1
knit - b9 1
knit - f8 1
miss - f7 1
;pass: 116 
knit + b7 2
knit + f9 2
knit + f10 2
knit + b13 2
knit + b14 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + b19 2
knit + b21 2
knit + f22 2
knit + f23 2
knit + f24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f29 2
knit + f30 2
knit + b31 2
knit + b32 2
knit + b33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + b39 2
knit + b40 2
knit + f41 2
knit + f42 2
knit + f43 2
;pass: 117 
knit - b43 3
knit - b41 3
knit - b38 3
knit - b37 3
knit - b35 3
knit - b34 3
knit - b32 3
knit - b29 3
knit - b28 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - b22 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - b17 3
knit - b16 3
knit - b14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit - b10 3
knit - b8 3
knit - f7 3
;pass: 118 
knit + f7 1
knit + f8 1
knit + b9 1
knit + b11 1
knit + b12 1
knit + f13 1
knit + f14 1
knit + b15 1
knit + b18 1
knit + f20 1
knit + f21 1
knit + b24 1
knit + b27 1
knit + b30 1
knit + f31 1
knit + f32 1
knit + b33 1
knit + b36 1
knit + f38 1
knit + f39 1
knit + b42 1
miss + f43 1
;pass: 119 
knit - f43 2
knit - f42 2
knit - b40 2
knit - b39 2
knit - b37 2
knit - f36 2
knit - b34 2
knit - b31 2
knit - f29 2
knit - b28 2
knit - f25 2
knit - f24 2
knit - f23 2
knit - b22 2
knit - b21 2
knit - b20 2
knit - b19 2
knit - f17 2
knit - f16 2
knit - f15 2
knit - b13 2
knit - f11 2
knit - b10 2
knit - b7 2
;pass: 120 
knit + b8 3
knit + f9 3
knit + f10 3
knit + b11 3
knit + f12 3
knit + b14 3
knit + b16 3
knit + b17 3
knit + f18 3
knit + f19 3
knit + b20 3
knit + f22 3
knit + b23 3
knit + b25 3
knit + f26 3
knit + f27 3
knit + f28 3
knit + b29 3
knit + f30 3
knit + b32 3
knit + f33 3
knit + f34 3
knit + f35 3
knit + f37 3
knit + b38 3
knit + f40 3
knit + f41 3
knit + b43 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b7 f8
xfer b8 f9
rack -1
x-add-roller-advance 100
xfer f7 b8
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b43 f42
xfer b42 f41
rack 1
x-add-roller-advance 100
xfer f43 b42
rack 0
x-speed-number 100
;pass: 121 
knit - b42 1
knit - b41 1
knit - b39 1
knit - f37 1
knit - f36 1
knit - b35 1
knit - b33 1
knit - f31 1
knit - f30 1
knit - f29 1
knit - b27 1
knit - b26 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - b21 1
knit - b18 1
knit - f17 1
knit - f16 1
knit - b15 1
knit - b12 1
knit - b9 1
miss - f8 1
;pass: 122 
knit + b10 2
knit + f11 2
knit + f12 2
knit + b13 2
knit + f14 2
knit + f15 2
knit + b16 2
knit + f18 2
knit + f19 2
knit + b22 2
knit + b24 2
knit + f25 2
knit + f26 2
knit + b28 2
knit + b30 2
knit + b31 2
knit + b34 2
knit + b36 2
knit + b37 2
knit + f39 2
knit + b40 2
knit + f42 2
;pass: 123 
knit - f41 3
knit - f40 3
knit - f38 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - b29 3
knit - f28 3
knit - f27 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - f21 3
knit - f20 3
knit - b19 3
knit - b17 3
knit - b14 3
knit - f13 3
knit - b11 3
knit - f10 3
knit - f9 3
knit - f8 3
;pass: 124 
knit + b8 1
knit + b9 1
knit + b12 1
knit + f15 1
knit + f16 1
knit + b18 1
knit + b20 1
knit + b21 1
knit + f22 1
knit + f23 1
knit + f24 1
knit + b27 1
knit + f29 1
knit + f30 1
knit + f31 1
knit + b32 1
knit + f33 1
knit + b35 1
knit + b36 1
knit + f37 1
knit + b38 1
knit + b39 1
knit + f40 1
knit + f41 1
knit + b42 1
;pass: 125 
knit - f42 2
knit - b41 2
knit - b40 2
knit - b37 2
knit - f36 2
knit - f35 2
knit - b34 2
knit - b33 2
knit - b31 2
knit - b30 2
knit - f28 2
knit - f27 2
knit - f26 2
knit - f25 2
knit - b24 2
knit - b22 2
knit - f21 2
knit - f20 2
knit - f19 2
knit - f18 2
knit - b16 2
knit - b15 2
knit - f14 2
knit - f13 2
knit - f12 2
knit - f11 2
knit - f10 2
miss - f8 2
;pass: 126 
knit + f8 3
knit + f9 3
knit + b10 3
knit + b11 3
knit + b13 3
knit + b14 3
knit + f17 3
knit + b19 3
knit + b20 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + b28 3
knit + b29 3
knit + f32 3
knit + f34 3
knit + b35 3
knit + f38 3
knit + f39 3
knit + b41 3
miss + f42 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b8 f9
xfer b9 f10
rack -1
x-add-roller-advance 100
xfer f8 b9
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b42 f41
xfer b41 f40
rack 1
x-add-roller-advance 100
xfer f42 b41
rack 0
x-speed-number 100
;pass: 127 
knit - f41 1
knit - b39 1
knit - b38 1
knit - b36 1
knit - b33 1
knit - b32 1
knit - b30 1
knit - f29 1
knit - b27 1
knit - f24 1
knit - f23 1
knit - f22 1
knit - b21 1
knit - b18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - b12 1
knit - f10 1
knit - f9 1
;pass: 128 
knit + b9 2
knit + b10 2
knit + f11 2
knit + f12 2
knit + b13 2
knit + f14 2
knit + b15 2
knit + b16 2
knit + b17 2
knit + f18 2
knit + f19 2
knit + f21 2
knit + b22 2
knit + b24 2
knit + f25 2
knit + f26 2
knit + f27 2
knit + f28 2
knit + f30 2
knit + b31 2
knit + f33 2
knit + f34 2
knit + f35 2
knit + f36 2
knit + f37 2
knit + f40 2
miss + f41 2
;pass: 129 
knit - b41 3
knit - b40 3
knit - f39 3
knit - f38 3
knit - b37 3
knit - b35 3
knit - b34 3
knit - f32 3
knit - f31 3
knit - b29 3
knit - b28 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - f20 3
knit - b19 3
knit - b17 3
knit - b14 3
knit - f13 3
knit - b11 3
miss - f9 3
;pass: 130 
knit + f9 1
knit + f10 1
knit + b12 1
knit + f15 1
knit + f16 1
knit + f17 1
knit + f18 1
knit + b20 1
knit + b21 1
knit + f24 1
knit + f25 1
knit + b27 1
knit + b30 1
knit + b32 1
knit + b33 1
knit + b36 1
knit + b38 1
knit + f39 1
miss + f41 1
;pass: 131 
knit - f41 2
knit - f40 2
knit - b39 2
knit - b37 2
knit - f36 2
knit - f35 2
knit - f34 2
knit - f33 2
knit - b31 2
knit - f29 2
knit - f28 2
knit - f27 2
knit - b25 2
knit - b24 2
knit - f22 2
knit - f21 2
knit - b19 2
knit - b18 2
knit - b16 2
knit - b15 2
knit - f14 2
knit - b13 2
knit - f12 2
knit - f11 2
knit - b10 2
knit - b9 2
;pass: 132 
knit + b11 3
knit + f13 3
knit + b14 3
knit + b17 3
knit + f19 3
knit + f20 3
knit + b22 3
knit + f23 3
knit + f26 3
knit + b28 3
knit + b29 3
knit + f30 3
knit + f31 3
knit + f32 3
knit + b34 3
knit + b35 3
knit + f37 3
knit + f38 3
knit + b40 3
knit + b41 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b9 f10
xfer b10 f11
rack -1
x-add-roller-advance 100
xfer f9 b10
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b41 f40
xfer b40 f39
rack 1
x-add-roller-advance 100
xfer f41 b40
rack 0
x-speed-number 100
;pass: 133 
knit - f39 1
knit - b38 1
knit - b36 1
knit - b33 1
knit - f32 1
knit - f31 1
knit - b30 1
knit - b27 1
knit - b26 1
knit - f25 1
knit - f24 1
knit - b23 1
knit - b21 1
knit - b20 1
knit - b18 1
knit - f17 1
knit - f16 1
knit - f15 1
knit - f14 1
knit - b12 1
miss - f10 1
;pass: 134 
knit + b10 2
knit + f12 2
knit + f13 2
knit + b15 2
knit + b16 2
knit + f19 2
knit + f20 2
knit + f21 2
knit + f22 2
knit + b24 2
knit + b25 2
knit + f27 2
knit + f28 2
knit + b31 2
knit + b32 2
knit + f34 2
knit + f35 2
knit + b37 2
knit + b39 2
knit + b40 2
;pass: 135 
knit - f40 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - b35 3
knit - b34 3
knit - f33 3
knit - b32 3
knit - f30 3
knit - f29 3
knit - b28 3
knit - f26 3
knit - f23 3
knit - b22 3
knit - b20 3
knit - b19 3
knit - f18 3
knit - b17 3
knit - b14 3
knit - b13 3
knit - f11 3
knit - f10 3
;pass: 136 
knit + f11 1
knit + b12 1
knit + b15 1
knit + f17 1
knit + f18 1
knit + f21 1
knit + b23 1
knit + f24 1
knit + f25 1
knit + f26 1
knit + f27 1
knit + f28 1
knit + b29 1
knit + b30 1
knit + f31 1
knit + f32 1
knit + f33 1
knit + f34 1
knit + f35 1
knit + b36 1
knit + b38 1
knit + f39 1
knit + f40 1
;pass: 137 
knit - b40 2
knit - b39 2
knit - f38 2
knit - b37 2
knit - b34 2
knit - b33 2
knit - b31 2
knit - f29 2
knit - b28 2
knit - b27 2
knit - b26 2
knit - b25 2
knit - b24 2
knit - f22 2
knit - b21 2
knit - f19 2
knit - b18 2
knit - b16 2
knit - f15 2
knit - f13 2
knit - f12 2
knit - b11 2
knit - b10 2
;pass: 138 
knit + f10 3
knit + b11 3
knit + b13 3
knit + f14 3
knit + f16 3
knit + b17 3
knit + b19 3
knit + f20 3
knit + b22 3
knit + f23 3
knit + b26 3
knit + b29 3
knit + f30 3
knit + b32 3
knit + b35 3
knit + f36 3
knit + f37 3
knit + b38 3
miss + f40 3
x-speed-number 100
;dec 1 on left
rack 1
x-add-roller-advance 150
xfer b10 f11
xfer b11 f12
rack -1
x-add-roller-advance 100
xfer f10 b11
rack 0
;dec 1 on right
rack -1
x-add-roller-advance 150
xfer b40 f39
xfer b39 f38
rack 1
x-add-roller-advance 100
xfer f40 b39
rack 0
x-speed-number 100
;pass: 139 
knit - b39 1
knit - f37 1
knit - b36 1
knit - f34 1
knit - f33 1
knit - f30 1
knit - f27 1
knit - f26 1
knit - f24 1
knit - f23 1
knit - b21 1
knit - f20 1
knit - b18 1
knit - b15 1
knit - b14 1
knit - b12 1
knit - f11 1
;pass: 140 
knit + b13 2
knit + f15 2
knit + f16 2
knit + f17 2
knit + f18 2
knit + b19 2
knit + b20 2
knit + b22 2
knit + b23 2
knit + b24 2
knit + f25 2
knit + b27 2
knit + b28 2
knit + b30 2
knit + b31 2
knit + f32 2
knit + b33 2
knit + b34 2
knit + b37 2
knit + f39 2
;pass: 141 
knit - f38 3
knit - f36 3
knit - f35 3
knit - b32 3
knit - f31 3
knit - f29 3
knit - f28 3
knit - b26 3
knit - b25 3
knit - b23 3
knit - f22 3
knit - f21 3
knit - b20 3
knit - f19 3
knit - b17 3
knit - b16 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - b11 3
;pass: 142 
knit + b12 1
knit + f13 1
knit + f14 1
knit + b15 1
knit + b18 1
knit + f20 1
knit + b21 1
knit + f22 1
knit + f23 1
knit + b24 1
knit + f27 1
knit + f28 1
knit + f29 1
knit + f30 1
knit + b33 1
knit + f35 1
knit + f36 1
knit + f37 1
knit + b38 1
knit + b39 1
miss + f45 1
;pass: 143 
knit - f38 2
knit - b37 2
knit - b36 2
knit - b35 2
knit - f34 2
knit - f33 2
knit - f32 2
knit - f31 2
knit - b30 2
knit - b29 2
knit - b28 2
knit - b27 2
knit - f26 2
knit - f25 2
knit - f24 2
knit - b22 2
knit - b19 2
knit - f16 2
knit - f15 2
knit - b14 2
knit - b13 2
miss - f11 2
out 2
;pass: 144 
knit + f11 3
knit + f12 3
knit + b14 3
knit + b16 3
knit + f17 3
knit + f18 3
knit + f19 3
knit + b20 3
knit + f21 3
knit + b23 3
knit + b25 3
knit + b26 3
knit + b29 3
knit + b31 3
knit + b32 3
knit + b34 3
knit + b35 3
knit + b38 3
knit + f39 3
;bindoff section
x-speed-number 100
x-roller-advance 100
knit - f39 3
knit - f38 3
knit - f37 3
knit - f36 3
knit - f35 3
knit - f34 3
knit - f33 3
knit - f32 3
knit - f31 3
knit - f30 3
knit - f29 3
knit - f28 3
knit - f27 3
knit - f26 3
knit - f25 3
knit - f24 3
knit - f23 3
knit - f22 3
knit - f21 3
knit - f20 3
knit - f19 3
knit - f18 3
knit - f17 3
knit - f16 3
knit - f15 3
knit - f14 3
knit - f13 3
knit - f12 3
knit - f11 3
knit + b11 3
knit + b12 3
knit + b13 3
knit + b14 3
knit + b15 3
knit + b16 3
knit + b17 3
knit + b18 3
knit + b19 3
knit + b20 3
knit + b21 3
knit + b22 3
knit + b23 3
knit + b24 3
knit + b25 3
knit + b26 3
knit + b27 3
knit + b28 3
knit + b29 3
knit + b30 3
knit + b31 3
knit + b32 3
knit + b33 3
knit + b34 3
knit + b35 3
knit + b36 3
knit + b37 3
knit + b38 3
knit + b39 3
xfer f39 b39
xfer f38 b38
xfer f37 b37
xfer f36 b36
xfer f35 b35
xfer f34 b34
xfer f33 b33
xfer f32 b32
xfer f31 b31
xfer f30 b30
xfer f29 b29
xfer f28 b28
xfer f27 b27
xfer f26 b26
xfer f25 b25
xfer f24 b24
xfer f23 b23
xfer f22 b22
xfer f21 b21
xfer f20 b20
xfer f19 b19
xfer f18 b18
xfer f17 b17
xfer f16 b16
xfer f15 b15
xfer f14 b14
xfer f13 b13
xfer f12 b12
xfer f11 b11
x-roller-advance 50
x-add-roller-advance -50
tuck + b40 3
knit - b39 3
xfer b39 f39
rack 1
xfer f39 b38
rack 0
knit - b38 3
tuck + b39 3
drop b40
xfer b38 f38
rack 1
xfer f38 b37
rack 0
x-add-roller-advance -50
drop b39
knit - b37 3
tuck + b38 3
xfer b37 f37
rack 1
xfer f37 b36
rack 0
x-add-roller-advance -50
drop b38
knit - b36 3
tuck + b37 3
xfer b36 f36
rack 1
xfer f36 b35
rack 0
x-add-roller-advance -50
drop b37
knit - b35 3
tuck + b36 3
xfer b35 f35
rack 1
xfer f35 b34
rack 0
x-add-roller-advance -50
drop b36
knit - b34 3
tuck + b35 3
xfer b34 f34
rack 1
xfer f34 b33
rack 0
x-add-roller-advance -50
drop b35
knit - b33 3
tuck + b34 3
xfer b33 f33
rack 1
xfer f33 b32
rack 0
x-add-roller-advance -50
drop b34
knit - b32 3
tuck + b33 3
xfer b32 f32
rack 1
xfer f32 b31
rack 0
x-add-roller-advance -50
drop b33
knit - b31 3
tuck + b32 3
xfer b31 f31
rack 1
xfer f31 b30
rack 0
x-add-roller-advance -50
drop b32
knit - b30 3
tuck + b31 3
xfer b30 f30
rack 1
xfer f30 b29
rack 0
x-add-roller-advance -50
drop b31
knit - b29 3
tuck + b30 3
xfer b29 f29
rack 1
xfer f29 b28
rack 0
x-add-roller-advance -50
drop b30
knit - b28 3
tuck + b29 3
xfer b28 f28
rack 1
xfer f28 b27
rack 0
x-add-roller-advance -50
drop b29
knit - b27 3
tuck + b28 3
xfer b27 f27
rack 1
xfer f27 b26
rack 0
x-add-roller-advance -50
drop b28
knit - b26 3
tuck + b27 3
xfer b26 f26
rack 1
xfer f26 b25
rack 0
x-add-roller-advance -50
drop b27
knit - b25 3
tuck + b26 3
xfer b25 f25
rack 1
xfer f25 b24
rack 0
x-add-roller-advance -50
drop b26
knit - b24 3
tuck + b25 3
xfer b24 f24
rack 1
xfer f24 b23
rack 0
x-add-roller-advance -50
drop b25
knit - b23 3
tuck + b24 3
xfer b23 f23
rack 1
xfer f23 b22
rack 0
x-add-roller-advance -50
drop b24
knit - b22 3
tuck + b23 3
xfer b22 f22
rack 1
xfer f22 b21
rack 0
x-add-roller-advance -50
drop b23
knit - b21 3
tuck + b22 3
xfer b21 f21
rack 1
xfer f21 b20
rack 0
x-add-roller-advance -50
drop b22
knit - b20 3
tuck + b21 3
xfer b20 f20
rack 1
xfer f20 b19
rack 0
x-add-roller-advance -50
drop b21
knit - b19 3
tuck + b20 3
xfer b19 f19
rack 1
xfer f19 b18
rack 0
x-add-roller-advance -50
drop b20
knit - b18 3
tuck + b19 3
xfer b18 f18
rack 1
xfer f18 b17
rack 0
x-add-roller-advance -50
drop b19
knit - b17 3
tuck + b18 3
xfer b17 f17
rack 1
xfer f17 b16
rack 0
x-add-roller-advance -50
drop b18
knit - b16 3
tuck + b17 3
xfer b16 f16
rack 1
xfer f16 b15
rack 0
x-add-roller-advance -50
drop b17
knit - b15 3
tuck + b16 3
xfer b15 f15
rack 1
xfer f15 b14
rack 0
x-add-roller-advance -50
drop b16
knit - b14 3
tuck + b15 3
xfer b14 f14
rack 1
xfer f14 b13
rack 0
x-add-roller-advance -50
drop b15
knit - b13 3
tuck + b14 3
xfer b13 f13
rack 1
xfer f13 b12
rack 0
x-add-roller-advance -50
drop b14
knit - b12 3
tuck + b13 3
xfer b12 f12
rack 1
xfer f12 b11
rack 0
x-add-roller-advance -50
drop b13
knit - b11 3
out 4
out 1
;tail
x-roller-advance 200
miss - b10 3
knit + b11 3
miss + b12 3
knit - b11 3
miss - b10 3
knit + b11 3
miss + b12 3
knit - b11 3
miss - b10 3
knit + b11 3
miss + b12 3
knit - b11 3
miss - b10 3
knit + b11 3
miss + b12 3
knit - b11 3
miss - b10 3
knit + b11 3
miss + b12 3
knit - b11 3
miss - b10 3
knit + b11 3
miss + b12 3
knit - b11 3
miss - b10 3
out 3
x-add-roller-advance 200
drop b11