;!knitout-2
;;Machine: Kniterate
;;Gauge: 7
;;Carriers: 1 2 3 4 5 6

in 6
tuck + f-10 6
tuck + f-8 6
tuck + f-6 6
tuck + f-4 6
tuck + f-2 6
tuck + f0 6
tuck + f2 6
tuck + f4 6
tuck + f6 6

tuck - f7 6
tuck - f5 6
tuck - f3 6
tuck - f1 6
tuck - f-1 6
tuck - f-3 6
tuck - f-5 6
tuck - f-7 6


knit + f-10 6
knit + f-9 6
knit + f-8 6
knit + f-7 6
knit + f-6 6
knit + f-5 6
knit + f-4 6
knit + f-3 6
knit + f-2 6
knit + f-1 6
knit + f0 6
knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6

knit - f7 6
knit - f6 6
knit - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6
knit - f0 6
knit - f-1 6
knit - f-2 6
knit - f-3 6
knit - f-4 6
knit - f-5 6
knit - f-6 6
knit - f-7 6
knit - f-8 6
knit - f-9 6
knit - f-10 6

out 6

drop f7
drop f6
drop f5
drop f4
drop f3
drop f2
drop f1
drop f0
drop f-1
drop f-2
drop f-3
drop f-4
drop f-5
drop f-6
drop f-7
drop f-8
drop f-9
drop f-10
