;!knitout-2
;;Machine: Kniterate
;;Gauge: 7
;;Position: Keep
;;Carriers: 1 2 3 4 5 6

in 6
tuck + f1 6
tuck + f3 6
tuck + f5 6
tuck + f7 6

tuck - f6 6
tuck - f4 6
tuck - f2 6

knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6

knit - f7 6
knit - f6 6
knit - f5 6
knit - f4 6
knit - f3 6
knit - f2 6
knit - f1 6

out 6

drop f7
drop f6
drop f5
drop f4
drop f3
drop f2
drop f1
