;!knitout-2
;;Machine: Kniterate
;;Gauge: 7
;;Position: Keep
;;Carriers: 1 2 3 4 5 6

in 6
tuck + f1 6
tuck + f3 6
tuck + f5 6
tuck + f7 6

tuck - f8 6
tuck - f6 6
tuck - f4 6
tuck - f2 6

knit + f1 6
knit + f2 6
knit + f3 6
knit + f4 6
knit + f5 6
knit + f6 6
knit + f7 6
knit + f8 6

xfer f1 b1
xfer f3 b3
xfer f5 b5
xfer f7 b7

knit - f8 6
knit - b7 6
knit - f6 6
knit - b5 6
knit - f4 6
knit - b3 6
knit - f2 6
knit - b1 6

xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8

knit + f1 6
knit + b2 6
knit + f3 6
knit + b4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + b8 6

xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8


x-xfer-style two-pass

knit - f8 6
knit - b7 6
knit - f6 6
knit - b5 6
knit - f4 6
knit - b3 6
knit - f2 6
knit - b1 6

xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8

knit + f1 6
knit + b2 6
knit + f3 6
knit + b4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + b8 6

xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8


x-xfer-style four-pass

knit - f8 6
knit - b7 6
knit - f6 6
knit - b5 6
knit - f4 6
knit - b3 6
knit - f2 6
knit - b1 6

xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8

knit + f1 6
knit + b2 6
knit + f3 6
knit + b4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + b8 6

xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8


knit - f8 6
knit - b7 6
knit - f6 6
knit - b5 6
knit - f4 6
knit - b3 6
knit - f2 6
knit - b1 6

x-xfer-style four-pass
xfer b1 f1
xfer f2 b2
xfer b3 f3
xfer f4 b4
x-xfer-style two-pass
xfer b5 f5
xfer f6 b6
xfer b7 f7
xfer f8 b8

knit + f1 6
knit + b2 6
knit + f3 6
knit + b4 6
knit + f5 6
knit + b6 6
knit + f7 6
knit + b8 6

x-xfer-style four-pass
xfer f1 b1
xfer b2 f2
xfer f3 b3
xfer b4 f4
x-xfer-style two-pass
xfer f5 b5
xfer b6 f6
xfer f7 b7
xfer b8 f8

out 6

drop f8
drop b7
drop f6
drop b5
drop f4
drop b3
drop f2
drop b1
